### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by PJH87** [xisiot/HyperETS#2]
`node ./app.js 
 Store path:/home/parallels/go/src/github.com/hyperledger/fabric/scripts/fabric-samples/HyperETS/organization/envAgency/hfc-key-store
 Store path:/home/parallels/go/src/github.com/hyperledger/fabric/scripts/fabric-samples/HyperETS/organization/tradingCenter/hfc-key-store
Successfully loaded admin from persistence
Assigned the admin user to the fabric client ::{"name":"admin","mspid":"AgencyMSP","roles":null,"affiliation":"","enrollmentSecret":"","enrollment":{"signingIdentity":"36e3991326d5d94b8775374a95332c3f375e064edf4c9d8634cd15a4fef23e82","identity":{"certificate":"-----BEGIN CERTIFICATE-----\nMIICBTCCAaygAwIBAgIUFR+KzfPoP7vuvqBqJvy49AZWqtcwCgYIKoZIzj0EAwIw\ndzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh\nbiBGcmFuY2lzY28xGzAZBgNVBAoTEmFnZW5jeS5leGFtcGxlLmNvbTEeMBwGA1UE\nAxMVY2EuYWdlbmN5LmV4YW1wbGUuY29tMB4XDTE5MDkyMjIwNDIwMFoXDTIwMDky\nMTIwNDcwMFowITEPMA0GA1UECxMGY2xpZW50MQ4wDAYDVQQDEwVhZG1pbjBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABBTxsfKIRm9HeMLdOvPYyJ/5eND/R1lts4fW\n1DRPzZbOXyuZk0xZVeP49E3fRCiXtpErBx3KGvESTvDqW6LBtIyjbDBqMA4GA1Ud\nDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBR9uTPZdTs4gvxAlCLP\naOdgE7Ga1jArBgNVHSMEJDAigCDwjeJ9fUaujdHLArpDPEHDQ+rI5nIYCPjMzEi+\n/z8+XDAKBggqhkjOPQQDAgNHADBEAiB4v2ebJuFR+6EIMF7xK2CqVnPYjQPUeTtu\nN9B/MVvvqQIgF1MmxNRX1QuFzn1OzUuWdnYBUPCQUxppx/M2QIHf9sU=\n-----END CERTIFICATE-----\n"}}}
Successfully loaded admin from persistence
Assigned the admin user to the fabric client ::{"name":"admin","mspid":"CenterMSP","roles":null,"affiliation":"","enrollmentSecret":"","enrollment":{"signingIdentity":"fa93f26a19893897726fa7af13bd05f6e454457a0bc8d9d6a7a617d21b49d863","identity":{"certificate":"-----BEGIN CERTIFICATE-----\nMIICBjCCAaygAwIBAgIUAuZC35iP7ZNiYPLQZvQ56vNDqzowCgYIKoZIzj0EAwIw\ndzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh\nbiBGcmFuY2lzY28xGzAZBgNVBAoTEmNlbnRlci5leGFtcGxlLmNvbTEeMBwGA1UE\nAxMVY2EuY2VudGVyLmV4YW1wbGUuY29tMB4XDTE5MDkyMjIwNDIwMFoXDTIwMDky\nMTIwNDcwMFowITEPMA0GA1UECxMGY2xpZW50MQ4wDAYDVQQDEwVhZG1pbjBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABL3429KYHE+ly19agTNGOzLcm8Xu5YqRb4SH\n7RkeNQFqGWuOW0dYg17b7XTRXAYLUggkijggSXj5tpIkIk/ybYSjbDBqMA4GA1Ud\nDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRUxB85otWTFTFWGuN4\nvnQG1v/v1TArBgNVHSMEJDAigCB2CWOjr04GEUhepOOEd1yJRauNHeNqJZhnqdwG\np1DhsjAKBggqhkjOPQQDAgNIADBFAiEAk89MerjQZRPVzuvaG+xfAVbkT/j11FWF\nBTnUsdWVMxYCIG4W/KDjMqTkYUraK+RT7s1+ZwtGzivsGKxfczA7z0Fw\n-----END CERTIFICATE-----\n"}}}
server started, listen port: 9021
`

does not work in last step..

"cannot get / " message is displayed

how can I solve this problem?

**Comment by Dendiom** [comment]
Actually, when **server started, listen port: 9021** is displayed, the http server has been started successfully, it seems that you have called the url : localhost:9021/, however, we didn't provide this api, you can see **app.js** and find the available apis

**Comment by PJH87** [comment]
> Actually, when **server started, listen port: 9021** is displayed, the http server has been started successfully, it seems that you have called the url : localhost:9021/, however, we didn't provide this api, you can see **app.js** and find the available apis

thanks
